server:
  port: 8764
spring:
  application:
    name: eurekaclient
<<<<<<< HEAD
  cloud:
    bus:
      refresh:
        enabled: true
  kafka:
    bootstrap-servers: localhost:9092
name: liqingjun-jack
age: 28
=======
name: liqingjun-JACK
age: 31
>>>>>>> 5324565dd5e14fcd32cfc71d8e5efd25921c4ea7
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
